import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import { cn } from '@/utils/cn';
import { Provider as TooltipProvider } from '@/components/ui/tooltip';
import { NotificationProvider } from '@/components/ui/notification-provider';
import Header from '@/components/header';

const inter = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

const geistMono = localFont({
  src: './fonts/GeistMono[wght].woff2',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
      className={cn(inter.variable, geistMono.variable, 'antialiased')}
      data-oid='q0juv64'
    >
      <body className='bg-bg-white-0 text-text-strong-950' data-oid='mtoooo0'>
        <ThemeProvider attribute='class' data-oid='r.u5q3x'>
          <TooltipProvider data-oid='7wkb3rh'>
            <div className='flex min-h-screen flex-col' data-oid='kte63p7'>
              <Header data-oid='58n_ur6' />
              <main className='flex flex-1 flex-col' data-oid='kiw05a8'>
                {children}
              </main>
            </div>
          </TooltipProvider>
        </ThemeProvider>
        <NotificationProvider data-oid='c_kgsad' />
      </body>
    </html>
  );
}
